variables:
  IMAGE_NAME: docker-app
  REGISTRY: docker.anisa.local

stages:
  - build
  - deploy


build:
  stage: build
  image: docker
  script:
    - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin $REGISTRY
    # - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" $REGISTRY
    - docker build -t $REGISTRY/$IMAGE_NAME:$CI_PIPELINE_ID .
    - docker push $REGISTRY/$IMAGE_NAME:$CI_PIPELINE_ID

deploy:
  stage: deploy
  image: docker

  before_script:
    - ls -la
    - mkdir -p ~/.ssh
    - echo "$DEPLOYER_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - ls -la ~/.ssh
  script:
    - unset DOCKER_HOST
    - docker context create my-swarm --docker "host=ssh://milad@192.168.122.11"
    - docker context use my-swarm
    - docker node ls
    - docker stack rm $IMAGE_NAME || true
    - sleep 1
    - sed -i "s/latest/$CI_PIPELINE_ID/g" docker-compose.yml
    - cat docker-compose.yml
    - docker stack deploy -c docker-compose.yml $IMAGE_NAME
  needs:
    - job: build
  retry: 2


